### PR TITLE
Support loading text from url hash & update url on input

### LINKED ISSUE #32: Update URL with what is written in the playground

### PR DESCRIPTION
**Pull request by h7y**
Fixes
#32 & #33

### CODE REVIEW

**Review by thorn0 — APPROVED** [review]

**Comment by h7y** [comment]
@lipis is this okay?

**Comment by dwelle** [comment]
Looks good.

I'd probably namespace it under a key though lest we want to use the `location.hash` for other things in the future. Maybe `#playground=`?

You can use `URLSearchParams` for both decoding and encoding.

```
// get
new URLSearchParams(location.hash.slice(1)).get('playground');
// set
const params = new URLSearchParams();
params.set('playground', event.target.value);
location.hash = params.toString();
```

**Comment by h7y** [comment]
> Looks good.
> 
> I'd probably namespace it under a key though lest we want to use the `location.hash` for other things in the future. Maybe `#playground=`?
> 
> You can use `URLSearchParams` for both decoding and encoding.
> 
> ```js
> // get
> new URLSearchParams(location.hash.slice(1)).get('playground');
> // set
> const params = new URLSearchParams();
> params.set('playground', event.target.value);
> location.hash = params.toString();
> ```

Done! :)

**Comment by dwelle** [comment]
Looking good. Thanks :)

**Pull request merged**
