### PR TITLE
Add favicon

### LINKED ISSUE #17: Add favicon.ico

### PR DESCRIPTION
**Pull request by harishcalvin**
Resolves #17

### CODE REVIEW

**Comment by lipis** [comment]
I was thinking to have maybe a `V` or something instead of Excalidraw logo...

**Comment by harishcalvin** [comment]
check this
logo-0

**Comment by lipis** [comment]
Yeah.. that looks nice.. maybe with a solid white background though..

**Comment by lipis** [comment]
Screenshot 2021-03-17 at 11 20 18 AM

Also could you create an .ico files with only those sizes: 48, 32, 16... no need for the 256 one

**Comment by harishcalvin** [comment]
like this? 
logo-1

**Comment by harishcalvin** [comment]
or like this? 
logo-1 1

**Comment by lipis** [comment]
The last one! White background.. not blue and not transparent.

**Comment by harishcalvin** [comment]
@lipis check 2a9518e8d5ba74431c4c85baff3b6096ae5624be

**Comment by lipis** [comment]
Looks good to me!

**Comment by lipis** [comment]
Thanks!

**Pull request merged**
