### PR TITLE
Fix Delta and Omega

### PR DESCRIPTION
**Pull request by thorn0**
The font had these glyphs, but they were assigned to wrong characters: 'INCREMENT' (U+2206) and 'OHM SIGN' (U+2126)
I copied the glyphs to the correct characters and used a trial beta version of FontLab to export to WOFF2.

I'm completely new to FontLab and font editing overall. There might exist a way to reuse the same glyph for multiple characters instead of copying it, but I don't know about it.

### CODE REVIEW

**Comment by dwelle** [comment]
LGMT. :heart: 

Before/after:

image image

**Review by dwelle — APPROVED** [review]

**Comment by lipis** [comment]
It's more like this when you write it though.. Screenshot 2021-02-28 at 5 49 43 PM

**Comment by lipis** [comment]
Δ looks good

**Comment by lipis** [comment]
Update only the source.. I'll export the woff2.. just read the initial comment.. for how it looks like we'll have it in another PR.

**Comment by dwelle** [comment]
> It's more like this when you write it though.. Screenshot 2021-02-28 at 5 49 43 PM

I've never seen it written like that (at least in my country), but even if that's how you wrote it by hand, we don't have to stick to these optimizations.

**Comment by lipis** [comment]
No greek is writing it this way though.. :) At least in my country :D (Greece)
tumblr_lve8sxPJjU1r3t8vbo1_500

**Comment by lipis** [comment]
But I also understand that it could be used in some Math formulas.. an noone would get it.. (except greeks).. so maybe it's better this way on a second thought.

**Comment by lipis** [comment]
Actually the woff2 is the same... I was confused with the 0 diff

**Comment by thorn0** [comment]
> Actually the woff2 is the same

GitHub doesn't know how to show a diff for this file, but it's not the same. E.g. the size has changed: 65704 → 65748

**Pull request merged**
